/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (number 62), U7[4]/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 16U    /*!<@brief PORTB pin index: 16 */
                                                /* @} */

/*! @name PORTB17 (number 63), U10[1]/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 17U    /*!<@brief PORTB pin index: 17 */
                                                /* @} */

/*! @name PORTC16 (number 90), J1[2]
  @{ */
#define BOARD_INITPINS_TMR_1588_0_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_TMR_1588_0_PIN 16U    /*!<@brief PORTC pin index: 16 */
                                             /* @} */

/*! @name PORTC17 (number 91), J1[4]
  @{ */
#define BOARD_INITPINS_TMR_1588_1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_TMR_1588_1_PIN 17U    /*!<@brief PORTC pin index: 17 */
                                             /* @} */

/*! @name PORTB1 (number 54), U13[11]/RMII0_MDC
  @{ */
#define BOARD_INITPINS_RMII0_MDC_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RMII0_MDC_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                            /* @} */

/*! @name PORTB0 (number 53), U13[10]/RMII0_MDIO
  @{ */
#define BOARD_INITPINS_RMII0_MDIO_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RMII0_MDIO_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                             /* @} */

/*! @name PORTA12 (number 42), U13[12]/RMII0_RXD_1
  @{ */
#define BOARD_INITPINS_RMII0_RXD1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_RXD1_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                             /* @} */

/*! @name PORTA13 (number 43), U13[13]/RMII0_RXD_0
  @{ */
#define BOARD_INITPINS_RMII0_RXD0_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_RXD0_PIN 13U    /*!<@brief PORTA pin index: 13 */
                                             /* @} */

/*! @name PORTA14 (number 44), U13[15]/RMII0_CRS_DV
  @{ */
#define BOARD_INITPINS_RMII0_CRS_DV_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_CRS_DV_PIN 14U    /*!<@brief PORTA pin index: 14 */
                                               /* @} */

/*! @name PORTA15 (number 45), U13[19]/RMII0_TXEN
  @{ */
#define BOARD_INITPINS_RMII0_TXEN_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_TXEN_PIN 15U    /*!<@brief PORTA pin index: 15 */
                                             /* @} */

/*! @name PORTA17 (number 47), U13[21]/RMII0_TXD1
  @{ */
#define BOARD_INITPINS_RMII0_TXD1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_TXD1_PIN 17U    /*!<@brief PORTA pin index: 17 */
                                             /* @} */

/*! @name PORTA16 (number 46), U13[20]/RMII0_TXD0
  @{ */
#define BOARD_INITPINS_RMII0_TXD0_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_TXD0_PIN 16U    /*!<@brief PORTA pin index: 16 */
                                             /* @} */

/*! @name PORTA5 (number 39), U13[17]/RMII0_RXER
  @{ */
#define BOARD_INITPINS_RMII0_RXER_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_RMII0_RXER_PIN 5U     /*!<@brief PORTA pin index: 5 */
                                             /* @} */

/*! @name PORTA4 (number 38), SW3
  @{ */
#define BOARD_INITPINS_SW3_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_SW3_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_SW3_PIN 4U     /*!<@brief PORTA pin index: 4 */
                                      /* @} */

/*! @name PORTB22 (number 68), D12[1]/LEDRGB_RED
  @{ */
#define BOARD_INITPINS_LED_RED_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_RED_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_RED_PIN 22U    /*!<@brief PORTB pin index: 22 */
                                          /* @} */

/*! @name PORTD2 (number 95), J2[8]
  @{ */
#define BOARD_INITPINS_UART2_RX_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_UART2_RX_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                           /* @} */

/*! @name PORTD3 (number 96), J2[10]
  @{ */
#define BOARD_INITPINS_UART2_TX_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_UART2_TX_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                           /* @} */

/*! @name PORTC12 (number 84), J2[2]
  @{ */
#define BOARD_INITPINS_BUSY_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_BUSY_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_BUSY_PIN 12U    /*!<@brief PORTC pin index: 12 */
                                       /* @} */

/*! @name PORTC3 (number 73), J1[16]
  @{ */
#define BOARD_INITPINS_RST_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_RST_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_RST_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                      /* @} */

/*! @name PORTC2 (number 72), J1[14]
  @{ */
#define BOARD_INITPINS_DC_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_DC_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_DC_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
